include build/target/board/generic_x86_64_a/BoardConfig.mk

TARGET_NO_KERNEL := false
TARGET_NO_RECOVERY := false
BOARD_USES_RECOVERY_AS_BOOT := false
BOARD_BUILD_SYSTEM_ROOT_IMAGE := true

BOARD_AVB_ENABLE := false

# system.img
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2147483648
BOARD_SYSTEMIMAGE_JOURNAL_SIZE := 0
BOARD_SYSTEMIMAGE_EXTFS_INODE_COUNT := 4096

# userdata.img
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_USERDATAIMAGE_PARTITION_SIZE := 12256784384
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4

# boot.img
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216

TARGET_COPY_OUT_VENDOR := vendor

BOARD_CACHEIMAGE_PARTITION_SIZE := 134217728

BOARD_FLASH_BLOCK_SIZE := 2048
